// ABI bindings are generated by build.rs into this directory.
// Each file is generated from its corresponding abi/*.json file.
#[allow(clippy::all)]
pub mod factory;
#[allow(clippy::all)]
pub mod pool;
#[allow(clippy::all)]
pub mod erc20;
